CREATE TABLE IF NOT EXISTS arenas
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL,
  map_base_pt_id INT NOT NULL,
  INDEX name_i(name),
  UNIQUE(name)) ENGINE=MyISAM;
CREATE TABLE IF NOT EXISTS regions
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL,
  world_id INT UNSIGNED NOT NULL,
  p1_id INT UNSIGNED NOT NULL,
  p2_id INT UNSIGNED NOT NULL,
  py_id INT UNSIGNED NOT NULL) ENGINE=MyISAM;
CREATE TABLE IF NOT EXISTS points
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL,
  xz POINT NOT NULL,
  y INT NOT NULL,
  z INT NOT NULL,
  server_id INT UNSIGNED NOT NULL,
  world_id INT UNSIGNED NOT NULL) ENGINE=MyISAM;
CREATE TABLE IF NOT EXISTS arena_region_assoc
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  arena_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  INDEX arena_id_i(arena_id)) ENGINE=MyISAM;
CREATE TABLE IF NOT EXISTS servers
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL) ENGINE=MyISAM;
CREATE TABLE IF NOT EXISTS worlds
  (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL) ENGINE=MyISAM;
DROP FUNCTION IF EXISTS CreateEnvelope;
DELIMITER $$
CREATE FUNCTION CreateEnvelope(p1 POINT, p2 POINT)
  RETURNS POLYGON DETERMINISTIC
  BEGIN DECLARE
    bounding POLYGON;
    SET bounding = Envelope(LineString(p1, p2));
    RETURN bounding;
  END$$